# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from auto_smart_factory/GripperState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import auto_smart_factory.msg

class GripperState(genpy.Message):
  _md5sum = "b937d7d47f113e6408c1ccaabb941455"
  _type = "auto_smart_factory/GripperState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# robot loaded or unloaded succesfully
bool loaded

# package
Package package

================================================================================
MSG: auto_smart_factory/Package
# the unique id of this package
uint32 id

# the id of the package type/configuration
uint32 type_id

"""
  __slots__ = ['loaded','package']
  _slot_types = ['bool','auto_smart_factory/Package']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       loaded,package

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GripperState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.loaded is None:
        self.loaded = False
      if self.package is None:
        self.package = auto_smart_factory.msg.Package()
    else:
      self.loaded = False
      self.package = auto_smart_factory.msg.Package()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2I().pack(_x.loaded, _x.package.id, _x.package.type_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.package is None:
        self.package = auto_smart_factory.msg.Package()
      end = 0
      _x = self
      start = end
      end += 9
      (_x.loaded, _x.package.id, _x.package.type_id,) = _get_struct_B2I().unpack(str[start:end])
      self.loaded = bool(self.loaded)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2I().pack(_x.loaded, _x.package.id, _x.package.type_id))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.package is None:
        self.package = auto_smart_factory.msg.Package()
      end = 0
      _x = self
      start = end
      end += 9
      (_x.loaded, _x.package.id, _x.package.type_id,) = _get_struct_B2I().unpack(str[start:end])
      self.loaded = bool(self.loaded)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2I = None
def _get_struct_B2I():
    global _struct_B2I
    if _struct_B2I is None:
        _struct_B2I = struct.Struct("<B2I")
    return _struct_B2I
