# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from auto_smart_factory/StorageUpdate.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import auto_smart_factory.msg
import genpy

class StorageUpdate(genpy.Message):
  _md5sum = "83cea01295e4c0b59e3822307599398d"
  _type = "auto_smart_factory/StorageUpdate"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# timestamp of the update
time stamp

# updated state
TrayState state

# The action that let to this update
uint8 UNKNOWN=0
uint8 RESERVATION=1
uint8 DERESERVATION=2
uint8 OCCUPATION=3
uint8 DEOCCUPATION=4

uint8 action


================================================================================
MSG: auto_smart_factory/TrayState
# the unique tray ID
uint32 id

# Indicates whether the tray is occupied or not.
bool occupied

# Availability of the tray. If false the the tray is allocated by a task.
bool available

# information about the package stored in this tray (only valid if state != free)
Package package


================================================================================
MSG: auto_smart_factory/Package
# the unique id of this package
uint32 id

# the id of the package type/configuration
uint32 type_id

"""
  # Pseudo-constants
  UNKNOWN = 0
  RESERVATION = 1
  DERESERVATION = 2
  OCCUPATION = 3
  DEOCCUPATION = 4

  __slots__ = ['stamp','state','action']
  _slot_types = ['time','auto_smart_factory/TrayState','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stamp,state,action

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StorageUpdate, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.state is None:
        self.state = auto_smart_factory.msg.TrayState()
      if self.action is None:
        self.action = 0
    else:
      self.stamp = genpy.Time()
      self.state = auto_smart_factory.msg.TrayState()
      self.action = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I2B2IB().pack(_x.stamp.secs, _x.stamp.nsecs, _x.state.id, _x.state.occupied, _x.state.available, _x.state.package.id, _x.state.package.type_id, _x.action))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.state is None:
        self.state = auto_smart_factory.msg.TrayState()
      end = 0
      _x = self
      start = end
      end += 23
      (_x.stamp.secs, _x.stamp.nsecs, _x.state.id, _x.state.occupied, _x.state.available, _x.state.package.id, _x.state.package.type_id, _x.action,) = _get_struct_3I2B2IB().unpack(str[start:end])
      self.state.occupied = bool(self.state.occupied)
      self.state.available = bool(self.state.available)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I2B2IB().pack(_x.stamp.secs, _x.stamp.nsecs, _x.state.id, _x.state.occupied, _x.state.available, _x.state.package.id, _x.state.package.type_id, _x.action))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.stamp is None:
        self.stamp = genpy.Time()
      if self.state is None:
        self.state = auto_smart_factory.msg.TrayState()
      end = 0
      _x = self
      start = end
      end += 23
      (_x.stamp.secs, _x.stamp.nsecs, _x.state.id, _x.state.occupied, _x.state.available, _x.state.package.id, _x.state.package.type_id, _x.action,) = _get_struct_3I2B2IB().unpack(str[start:end])
      self.state.occupied = bool(self.state.occupied)
      self.state.available = bool(self.state.available)
      self.stamp.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I2B2IB = None
def _get_struct_3I2B2IB():
    global _struct_3I2B2IB
    if _struct_3I2B2IB is None:
        _struct_3I2B2IB = struct.Struct("<3I2B2IB")
    return _struct_3I2B2IB
