(cl:in-package auto_smart_factory-srv)
(cl:export '(WAREHOUSE_CONFIGURATION-VAL
          WAREHOUSE_CONFIGURATION
          ROBOT_CONFIGURATIONS-VAL
          ROBOT_CONFIGURATIONS
          PACKAGE_CONFIGURATIONS-VAL
          PACKAGE_CONFIGURATIONS
          SUCCESS-VAL
          SUCCESS
))