// Generated by gencpp from file auto_smart_factory/AssignChargingTask.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_ASSIGNCHARGINGTASK_H
#define AUTO_SMART_FACTORY_MESSAGE_ASSIGNCHARGINGTASK_H

#include <ros/service_traits.h>


#include <auto_smart_factory/AssignChargingTaskRequest.h>
#include <auto_smart_factory/AssignChargingTaskResponse.h>


namespace auto_smart_factory
{

struct AssignChargingTask
{

typedef AssignChargingTaskRequest Request;
typedef AssignChargingTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AssignChargingTask
} // namespace auto_smart_factory


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_smart_factory::AssignChargingTask > {
  static const char* value()
  {
    return "dd6c73c96eadb2e66af831949e40763a";
  }

  static const char* value(const ::auto_smart_factory::AssignChargingTask&) { return value(); }
};

template<>
struct DataType< ::auto_smart_factory::AssignChargingTask > {
  static const char* value()
  {
    return "auto_smart_factory/AssignChargingTask";
  }

  static const char* value(const ::auto_smart_factory::AssignChargingTask&) { return value(); }
};


// service_traits::MD5Sum< ::auto_smart_factory::AssignChargingTaskRequest> should match 
// service_traits::MD5Sum< ::auto_smart_factory::AssignChargingTask > 
template<>
struct MD5Sum< ::auto_smart_factory::AssignChargingTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::AssignChargingTask >::value();
  }
  static const char* value(const ::auto_smart_factory::AssignChargingTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::AssignChargingTaskRequest> should match 
// service_traits::DataType< ::auto_smart_factory::AssignChargingTask > 
template<>
struct DataType< ::auto_smart_factory::AssignChargingTaskRequest>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::AssignChargingTask >::value();
  }
  static const char* value(const ::auto_smart_factory::AssignChargingTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_smart_factory::AssignChargingTaskResponse> should match 
// service_traits::MD5Sum< ::auto_smart_factory::AssignChargingTask > 
template<>
struct MD5Sum< ::auto_smart_factory::AssignChargingTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::AssignChargingTask >::value();
  }
  static const char* value(const ::auto_smart_factory::AssignChargingTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::AssignChargingTaskResponse> should match 
// service_traits::DataType< ::auto_smart_factory::AssignChargingTask > 
template<>
struct DataType< ::auto_smart_factory::AssignChargingTaskResponse>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::AssignChargingTask >::value();
  }
  static const char* value(const ::auto_smart_factory::AssignChargingTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_ASSIGNCHARGINGTASK_H
