// Generated by gencpp from file auto_smart_factory/GetLocalPathRequest.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_GETLOCALPATHREQUEST_H
#define AUTO_SMART_FACTORY_MESSAGE_GETLOCALPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <auto_smart_factory/RobotConfiguration.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace auto_smart_factory
{
template <class ContainerAllocator>
struct GetLocalPathRequest_
{
  typedef GetLocalPathRequest_<ContainerAllocator> Type;

  GetLocalPathRequest_()
    : agent_id()
    , robots_path()
    , robot_config()
    , next_position()
    , goal_position()
    , robot_position()
    , obstacles()  {
    }
  GetLocalPathRequest_(const ContainerAllocator& _alloc)
    : agent_id(_alloc)
    , robots_path(_alloc)
    , robot_config(_alloc)
    , next_position(_alloc)
    , goal_position(_alloc)
    , robot_position(_alloc)
    , obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _agent_id_type;
  _agent_id_type agent_id;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _robots_path_type;
  _robots_path_type robots_path;

   typedef  ::auto_smart_factory::RobotConfiguration_<ContainerAllocator>  _robot_config_type;
  _robot_config_type robot_config;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _next_position_type;
  _next_position_type next_position;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _goal_position_type;
  _goal_position_type goal_position;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _robot_position_type;
  _robot_position_type robot_position;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;





  typedef boost::shared_ptr< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetLocalPathRequest_

typedef ::auto_smart_factory::GetLocalPathRequest_<std::allocator<void> > GetLocalPathRequest;

typedef boost::shared_ptr< ::auto_smart_factory::GetLocalPathRequest > GetLocalPathRequestPtr;
typedef boost::shared_ptr< ::auto_smart_factory::GetLocalPathRequest const> GetLocalPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db492bb913446481ce8c861eb7241b44";
  }

  static const char* value(const ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb492bb913446481ULL;
  static const uint64_t static_value2 = 0xce8c861eb7241b44ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/GetLocalPathRequest";
  }

  static const char* value(const ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string agent_id\n\
geometry_msgs/Point[] robots_path\n\
RobotConfiguration robot_config\n\
geometry_msgs/Point next_position\n\
geometry_msgs/Point goal_position\n\
geometry_msgs/Point robot_position\n\
\n\
\n\
geometry_msgs/Point[] obstacles\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: auto_smart_factory/RobotConfiguration\n\
# name of this robot type\n\
string type_name\n\
\n\
# charging rate of the battery\n\
float32 charging_rate\n\
\n\
# discharging rate of the battery\n\
float32 discharging_rate\n\
\n\
# minimum linear velocity in [m/s]\n\
float32 min_linear_vel\n\
\n\
# maximum linear velocity in [m/s]\n\
float32 max_linear_vel\n\
\n\
# maximum angular velocity in [rad/s]\n\
float32 max_angular_vel\n\
\n\
# maximum radius of the robot\n\
float32 radius\n\
\n\
# maximum package weight in [kg]\n\
float32 max_load\n\
";
  }

  static const char* value(const ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agent_id);
      stream.next(m.robots_path);
      stream.next(m.robot_config);
      stream.next(m.next_position);
      stream.next(m.goal_position);
      stream.next(m.robot_position);
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetLocalPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::GetLocalPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "agent_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.agent_id);
    s << indent << "robots_path[]" << std::endl;
    for (size_t i = 0; i < v.robots_path.size(); ++i)
    {
      s << indent << "  robots_path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.robots_path[i]);
    }
    s << indent << "robot_config: ";
    s << std::endl;
    Printer< ::auto_smart_factory::RobotConfiguration_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_config);
    s << indent << "next_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.next_position);
    s << indent << "goal_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_position);
    s << indent << "robot_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_position);
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_GETLOCALPATHREQUEST_H
