// Generated by gencpp from file auto_smart_factory/GetPackageConfigurationsResponse.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_GETPACKAGECONFIGURATIONSRESPONSE_H
#define AUTO_SMART_FACTORY_MESSAGE_GETPACKAGECONFIGURATIONSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <auto_smart_factory/PackageConfiguration.h>

namespace auto_smart_factory
{
template <class ContainerAllocator>
struct GetPackageConfigurationsResponse_
{
  typedef GetPackageConfigurationsResponse_<ContainerAllocator> Type;

  GetPackageConfigurationsResponse_()
    : configs()  {
    }
  GetPackageConfigurationsResponse_(const ContainerAllocator& _alloc)
    : configs(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >::other >  _configs_type;
  _configs_type configs;





  typedef boost::shared_ptr< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPackageConfigurationsResponse_

typedef ::auto_smart_factory::GetPackageConfigurationsResponse_<std::allocator<void> > GetPackageConfigurationsResponse;

typedef boost::shared_ptr< ::auto_smart_factory::GetPackageConfigurationsResponse > GetPackageConfigurationsResponsePtr;
typedef boost::shared_ptr< ::auto_smart_factory::GetPackageConfigurationsResponse const> GetPackageConfigurationsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c79e4d48272b30033eb439274215257";
  }

  static const char* value(const ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c79e4d48272b300ULL;
  static const uint64_t static_value2 = 0x33eb439274215257ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/GetPackageConfigurationsResponse";
  }

  static const char* value(const ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PackageConfiguration[] configs\n\
\n\
\n\
================================================================================\n\
MSG: auto_smart_factory/PackageConfiguration\n\
# package type id (!= package id)\n\
uint32 id\n\
\n\
# package dimensions\n\
float32 width\n\
float32 height\n\
\n\
# package weight\n\
float32 weight\n\
\n\
";
  }

  static const char* value(const ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.configs);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPackageConfigurationsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::GetPackageConfigurationsResponse_<ContainerAllocator>& v)
  {
    s << indent << "configs[]" << std::endl;
    for (size_t i = 0; i < v.configs.size(); ++i)
    {
      s << indent << "  configs[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >::stream(s, indent + "    ", v.configs[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_GETPACKAGECONFIGURATIONSRESPONSE_H
