// Generated by gencpp from file auto_smart_factory/GetPackageResponse.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_GETPACKAGERESPONSE_H
#define AUTO_SMART_FACTORY_MESSAGE_GETPACKAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <auto_smart_factory/Package.h>

namespace auto_smart_factory
{
template <class ContainerAllocator>
struct GetPackageResponse_
{
  typedef GetPackageResponse_<ContainerAllocator> Type;

  GetPackageResponse_()
    : pkg()  {
    }
  GetPackageResponse_(const ContainerAllocator& _alloc)
    : pkg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::auto_smart_factory::Package_<ContainerAllocator>  _pkg_type;
  _pkg_type pkg;





  typedef boost::shared_ptr< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetPackageResponse_

typedef ::auto_smart_factory::GetPackageResponse_<std::allocator<void> > GetPackageResponse;

typedef boost::shared_ptr< ::auto_smart_factory::GetPackageResponse > GetPackageResponsePtr;
typedef boost::shared_ptr< ::auto_smart_factory::GetPackageResponse const> GetPackageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "964ad4c4a68ecf41ce5ed223a2a4d2cc";
  }

  static const char* value(const ::auto_smart_factory::GetPackageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x964ad4c4a68ecf41ULL;
  static const uint64_t static_value2 = 0xce5ed223a2a4d2ccULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/GetPackageResponse";
  }

  static const char* value(const ::auto_smart_factory::GetPackageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Package pkg\n\
\n\
\n\
\n\
================================================================================\n\
MSG: auto_smart_factory/Package\n\
# the unique id of this package\n\
uint32 id\n\
\n\
# the id of the package type/configuration\n\
uint32 type_id\n\
\n\
";
  }

  static const char* value(const ::auto_smart_factory::GetPackageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pkg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetPackageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::GetPackageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::GetPackageResponse_<ContainerAllocator>& v)
  {
    s << indent << "pkg: ";
    s << std::endl;
    Printer< ::auto_smart_factory::Package_<ContainerAllocator> >::stream(s, indent + "  ", v.pkg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_GETPACKAGERESPONSE_H
