// Generated by gencpp from file auto_smart_factory/GetPackageConfigurations.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_GETPACKAGECONFIGURATIONS_H
#define AUTO_SMART_FACTORY_MESSAGE_GETPACKAGECONFIGURATIONS_H

#include <ros/service_traits.h>


#include <auto_smart_factory/GetPackageConfigurationsRequest.h>
#include <auto_smart_factory/GetPackageConfigurationsResponse.h>


namespace auto_smart_factory
{

struct GetPackageConfigurations
{

typedef GetPackageConfigurationsRequest Request;
typedef GetPackageConfigurationsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPackageConfigurations
} // namespace auto_smart_factory


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_smart_factory::GetPackageConfigurations > {
  static const char* value()
  {
    return "6c79e4d48272b30033eb439274215257";
  }

  static const char* value(const ::auto_smart_factory::GetPackageConfigurations&) { return value(); }
};

template<>
struct DataType< ::auto_smart_factory::GetPackageConfigurations > {
  static const char* value()
  {
    return "auto_smart_factory/GetPackageConfigurations";
  }

  static const char* value(const ::auto_smart_factory::GetPackageConfigurations&) { return value(); }
};


// service_traits::MD5Sum< ::auto_smart_factory::GetPackageConfigurationsRequest> should match 
// service_traits::MD5Sum< ::auto_smart_factory::GetPackageConfigurations > 
template<>
struct MD5Sum< ::auto_smart_factory::GetPackageConfigurationsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::GetPackageConfigurations >::value();
  }
  static const char* value(const ::auto_smart_factory::GetPackageConfigurationsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::GetPackageConfigurationsRequest> should match 
// service_traits::DataType< ::auto_smart_factory::GetPackageConfigurations > 
template<>
struct DataType< ::auto_smart_factory::GetPackageConfigurationsRequest>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::GetPackageConfigurations >::value();
  }
  static const char* value(const ::auto_smart_factory::GetPackageConfigurationsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_smart_factory::GetPackageConfigurationsResponse> should match 
// service_traits::MD5Sum< ::auto_smart_factory::GetPackageConfigurations > 
template<>
struct MD5Sum< ::auto_smart_factory::GetPackageConfigurationsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::GetPackageConfigurations >::value();
  }
  static const char* value(const ::auto_smart_factory::GetPackageConfigurationsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::GetPackageConfigurationsResponse> should match 
// service_traits::DataType< ::auto_smart_factory::GetPackageConfigurations > 
template<>
struct DataType< ::auto_smart_factory::GetPackageConfigurationsResponse>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::GetPackageConfigurations >::value();
  }
  static const char* value(const ::auto_smart_factory::GetPackageConfigurationsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_GETPACKAGECONFIGURATIONS_H
