// Generated by gencpp from file auto_smart_factory/GetTrayStateResponse.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_GETTRAYSTATERESPONSE_H
#define AUTO_SMART_FACTORY_MESSAGE_GETTRAYSTATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <auto_smart_factory/TrayState.h>

namespace auto_smart_factory
{
template <class ContainerAllocator>
struct GetTrayStateResponse_
{
  typedef GetTrayStateResponse_<ContainerAllocator> Type;

  GetTrayStateResponse_()
    : state()  {
    }
  GetTrayStateResponse_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::auto_smart_factory::TrayState_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTrayStateResponse_

typedef ::auto_smart_factory::GetTrayStateResponse_<std::allocator<void> > GetTrayStateResponse;

typedef boost::shared_ptr< ::auto_smart_factory::GetTrayStateResponse > GetTrayStateResponsePtr;
typedef boost::shared_ptr< ::auto_smart_factory::GetTrayStateResponse const> GetTrayStateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8fc1740bf5eaf110ae8d47041b731e7";
  }

  static const char* value(const ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8fc1740bf5eaf11ULL;
  static const uint64_t static_value2 = 0x0ae8d47041b731e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/GetTrayStateResponse";
  }

  static const char* value(const ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "TrayState state\n\
\n\
\n\
\n\
================================================================================\n\
MSG: auto_smart_factory/TrayState\n\
# the unique tray ID\n\
uint32 id\n\
\n\
# Indicates whether the tray is occupied or not.\n\
bool occupied\n\
\n\
# Availability of the tray. If false the the tray is allocated by a task.\n\
bool available\n\
\n\
# information about the package stored in this tray (only valid if state != free)\n\
Package package\n\
\n\
\n\
================================================================================\n\
MSG: auto_smart_factory/Package\n\
# the unique id of this package\n\
uint32 id\n\
\n\
# the id of the package type/configuration\n\
uint32 type_id\n\
\n\
";
  }

  static const char* value(const ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTrayStateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::GetTrayStateResponse_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::auto_smart_factory::TrayState_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_GETTRAYSTATERESPONSE_H
