// Generated by gencpp from file auto_smart_factory/inputRequestRequest.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_INPUTREQUESTREQUEST_H
#define AUTO_SMART_FACTORY_MESSAGE_INPUTREQUESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <auto_smart_factory/RobotConfiguration.h>

namespace auto_smart_factory
{
template <class ContainerAllocator>
struct inputRequestRequest_
{
  typedef inputRequestRequest_<ContainerAllocator> Type;

  inputRequestRequest_()
    : posStart()
    , idTrays()
    , idInput()
    , robot()  {
    }
  inputRequestRequest_(const ContainerAllocator& _alloc)
    : posStart(_alloc)
    , idTrays(_alloc)
    , idInput(_alloc)
    , robot(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _posStart_type;
  _posStart_type posStart;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _idTrays_type;
  _idTrays_type idTrays;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _idInput_type;
  _idInput_type idInput;

   typedef  ::auto_smart_factory::RobotConfiguration_<ContainerAllocator>  _robot_type;
  _robot_type robot;





  typedef boost::shared_ptr< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct inputRequestRequest_

typedef ::auto_smart_factory::inputRequestRequest_<std::allocator<void> > inputRequestRequest;

typedef boost::shared_ptr< ::auto_smart_factory::inputRequestRequest > inputRequestRequestPtr;
typedef boost::shared_ptr< ::auto_smart_factory::inputRequestRequest const> inputRequestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c5f1c61abfa9f0ec5f04789dee1a21a0";
  }

  static const char* value(const ::auto_smart_factory::inputRequestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc5f1c61abfa9f0ecULL;
  static const uint64_t static_value2 = 0x5f04789dee1a21a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/inputRequestRequest";
  }

  static const char* value(const ::auto_smart_factory::inputRequestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point posStart\n\
uint32[] idTrays\n\
uint32[] idInput\n\
RobotConfiguration robot\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: auto_smart_factory/RobotConfiguration\n\
# name of this robot type\n\
string type_name\n\
\n\
# charging rate of the battery\n\
float32 charging_rate\n\
\n\
# discharging rate of the battery\n\
float32 discharging_rate\n\
\n\
# minimum linear velocity in [m/s]\n\
float32 min_linear_vel\n\
\n\
# maximum linear velocity in [m/s]\n\
float32 max_linear_vel\n\
\n\
# maximum angular velocity in [rad/s]\n\
float32 max_angular_vel\n\
\n\
# maximum radius of the robot\n\
float32 radius\n\
\n\
# maximum package weight in [kg]\n\
float32 max_load\n\
";
  }

  static const char* value(const ::auto_smart_factory::inputRequestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.posStart);
      stream.next(m.idTrays);
      stream.next(m.idInput);
      stream.next(m.robot);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct inputRequestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::inputRequestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::inputRequestRequest_<ContainerAllocator>& v)
  {
    s << indent << "posStart: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.posStart);
    s << indent << "idTrays[]" << std::endl;
    for (size_t i = 0; i < v.idTrays.size(); ++i)
    {
      s << indent << "  idTrays[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.idTrays[i]);
    }
    s << indent << "idInput[]" << std::endl;
    for (size_t i = 0; i < v.idInput.size(); ++i)
    {
      s << indent << "  idInput[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.idInput[i]);
    }
    s << indent << "robot: ";
    s << std::endl;
    Printer< ::auto_smart_factory::RobotConfiguration_<ContainerAllocator> >::stream(s, indent + "  ", v.robot);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_INPUTREQUESTREQUEST_H
