// Generated by gencpp from file auto_smart_factory/inputRequest.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_INPUTREQUEST_H
#define AUTO_SMART_FACTORY_MESSAGE_INPUTREQUEST_H

#include <ros/service_traits.h>


#include <auto_smart_factory/inputRequestRequest.h>
#include <auto_smart_factory/inputRequestResponse.h>


namespace auto_smart_factory
{

struct inputRequest
{

typedef inputRequestRequest Request;
typedef inputRequestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct inputRequest
} // namespace auto_smart_factory


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_smart_factory::inputRequest > {
  static const char* value()
  {
    return "84b93cb25f9b147c760d7e90b220604b";
  }

  static const char* value(const ::auto_smart_factory::inputRequest&) { return value(); }
};

template<>
struct DataType< ::auto_smart_factory::inputRequest > {
  static const char* value()
  {
    return "auto_smart_factory/inputRequest";
  }

  static const char* value(const ::auto_smart_factory::inputRequest&) { return value(); }
};


// service_traits::MD5Sum< ::auto_smart_factory::inputRequestRequest> should match 
// service_traits::MD5Sum< ::auto_smart_factory::inputRequest > 
template<>
struct MD5Sum< ::auto_smart_factory::inputRequestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::inputRequest >::value();
  }
  static const char* value(const ::auto_smart_factory::inputRequestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::inputRequestRequest> should match 
// service_traits::DataType< ::auto_smart_factory::inputRequest > 
template<>
struct DataType< ::auto_smart_factory::inputRequestRequest>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::inputRequest >::value();
  }
  static const char* value(const ::auto_smart_factory::inputRequestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_smart_factory::inputRequestResponse> should match 
// service_traits::MD5Sum< ::auto_smart_factory::inputRequest > 
template<>
struct MD5Sum< ::auto_smart_factory::inputRequestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::inputRequest >::value();
  }
  static const char* value(const ::auto_smart_factory::inputRequestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::inputRequestResponse> should match 
// service_traits::DataType< ::auto_smart_factory::inputRequest > 
template<>
struct DataType< ::auto_smart_factory::inputRequestResponse>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::inputRequest >::value();
  }
  static const char* value(const ::auto_smart_factory::inputRequestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_INPUTREQUEST_H
