// Generated by gencpp from file auto_smart_factory/MovePackage.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_MOVEPACKAGE_H
#define AUTO_SMART_FACTORY_MESSAGE_MOVEPACKAGE_H

#include <ros/service_traits.h>


#include <auto_smart_factory/MovePackageRequest.h>
#include <auto_smart_factory/MovePackageResponse.h>


namespace auto_smart_factory
{

struct MovePackage
{

typedef MovePackageRequest Request;
typedef MovePackageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MovePackage
} // namespace auto_smart_factory


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_smart_factory::MovePackage > {
  static const char* value()
  {
    return "a13e62d7ae1d84e470f967fb93b69c6e";
  }

  static const char* value(const ::auto_smart_factory::MovePackage&) { return value(); }
};

template<>
struct DataType< ::auto_smart_factory::MovePackage > {
  static const char* value()
  {
    return "auto_smart_factory/MovePackage";
  }

  static const char* value(const ::auto_smart_factory::MovePackage&) { return value(); }
};


// service_traits::MD5Sum< ::auto_smart_factory::MovePackageRequest> should match 
// service_traits::MD5Sum< ::auto_smart_factory::MovePackage > 
template<>
struct MD5Sum< ::auto_smart_factory::MovePackageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::MovePackage >::value();
  }
  static const char* value(const ::auto_smart_factory::MovePackageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::MovePackageRequest> should match 
// service_traits::DataType< ::auto_smart_factory::MovePackage > 
template<>
struct DataType< ::auto_smart_factory::MovePackageRequest>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::MovePackage >::value();
  }
  static const char* value(const ::auto_smart_factory::MovePackageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_smart_factory::MovePackageResponse> should match 
// service_traits::MD5Sum< ::auto_smart_factory::MovePackage > 
template<>
struct MD5Sum< ::auto_smart_factory::MovePackageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::MovePackage >::value();
  }
  static const char* value(const ::auto_smart_factory::MovePackageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::MovePackageResponse> should match 
// service_traits::DataType< ::auto_smart_factory::MovePackage > 
template<>
struct DataType< ::auto_smart_factory::MovePackageResponse>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::MovePackage >::value();
  }
  static const char* value(const ::auto_smart_factory::MovePackageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_MOVEPACKAGE_H
