// Generated by gencpp from file auto_smart_factory/PackageConfiguration.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_PACKAGECONFIGURATION_H
#define AUTO_SMART_FACTORY_MESSAGE_PACKAGECONFIGURATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_smart_factory
{
template <class ContainerAllocator>
struct PackageConfiguration_
{
  typedef PackageConfiguration_<ContainerAllocator> Type;

  PackageConfiguration_()
    : id(0)
    , width(0.0)
    , height(0.0)
    , weight(0.0)  {
    }
  PackageConfiguration_(const ContainerAllocator& _alloc)
    : id(0)
    , width(0.0)
    , height(0.0)
    , weight(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef float _width_type;
  _width_type width;

   typedef float _height_type;
  _height_type height;

   typedef float _weight_type;
  _weight_type weight;





  typedef boost::shared_ptr< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> const> ConstPtr;

}; // struct PackageConfiguration_

typedef ::auto_smart_factory::PackageConfiguration_<std::allocator<void> > PackageConfiguration;

typedef boost::shared_ptr< ::auto_smart_factory::PackageConfiguration > PackageConfigurationPtr;
typedef boost::shared_ptr< ::auto_smart_factory::PackageConfiguration const> PackageConfigurationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cf7721bfc769026ba7e793cd9017b38";
  }

  static const char* value(const ::auto_smart_factory::PackageConfiguration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cf7721bfc769026ULL;
  static const uint64_t static_value2 = 0xba7e793cd9017b38ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/PackageConfiguration";
  }

  static const char* value(const ::auto_smart_factory::PackageConfiguration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# package type id (!= package id)\n\
uint32 id\n\
\n\
# package dimensions\n\
float32 width\n\
float32 height\n\
\n\
# package weight\n\
float32 weight\n\
\n\
";
  }

  static const char* value(const ::auto_smart_factory::PackageConfiguration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.width);
      stream.next(m.height);
      stream.next(m.weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PackageConfiguration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::PackageConfiguration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::PackageConfiguration_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "width: ";
    Printer<float>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "weight: ";
    Printer<float>::stream(s, indent + "  ", v.weight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_PACKAGECONFIGURATION_H
