// Generated by gencpp from file auto_smart_factory/PerformTaskTestRequest.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_PERFORMTASKTESTREQUEST_H
#define AUTO_SMART_FACTORY_MESSAGE_PERFORMTASKTESTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace auto_smart_factory
{
template <class ContainerAllocator>
struct PerformTaskTestRequest_
{
  typedef PerformTaskTestRequest_<ContainerAllocator> Type;

  PerformTaskTestRequest_()
    : task_id(0)
    , start_pos()
    , end_pos()  {
    }
  PerformTaskTestRequest_(const ContainerAllocator& _alloc)
    : task_id(0)
    , start_pos(_alloc)
    , end_pos(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _task_id_type;
  _task_id_type task_id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _start_pos_type;
  _start_pos_type start_pos;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _end_pos_type;
  _end_pos_type end_pos;





  typedef boost::shared_ptr< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PerformTaskTestRequest_

typedef ::auto_smart_factory::PerformTaskTestRequest_<std::allocator<void> > PerformTaskTestRequest;

typedef boost::shared_ptr< ::auto_smart_factory::PerformTaskTestRequest > PerformTaskTestRequestPtr;
typedef boost::shared_ptr< ::auto_smart_factory::PerformTaskTestRequest const> PerformTaskTestRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "347969e57f21de1f57df3ce7cb965f5c";
  }

  static const char* value(const ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x347969e57f21de1fULL;
  static const uint64_t static_value2 = 0x57df3ce7cb965f5cULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/PerformTaskTestRequest";
  }

  static const char* value(const ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 task_id\n\
geometry_msgs/Point start_pos\n\
geometry_msgs/Point end_pos\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_id);
      stream.next(m.start_pos);
      stream.next(m.end_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PerformTaskTestRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::PerformTaskTestRequest_<ContainerAllocator>& v)
  {
    s << indent << "task_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "start_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.start_pos);
    s << indent << "end_pos: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.end_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_PERFORMTASKTESTREQUEST_H
