// Generated by gencpp from file auto_smart_factory/PerformTaskTest.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_PERFORMTASKTEST_H
#define AUTO_SMART_FACTORY_MESSAGE_PERFORMTASKTEST_H

#include <ros/service_traits.h>


#include <auto_smart_factory/PerformTaskTestRequest.h>
#include <auto_smart_factory/PerformTaskTestResponse.h>


namespace auto_smart_factory
{

struct PerformTaskTest
{

typedef PerformTaskTestRequest Request;
typedef PerformTaskTestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PerformTaskTest
} // namespace auto_smart_factory


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_smart_factory::PerformTaskTest > {
  static const char* value()
  {
    return "190d24b4aa92517c4ea4ac2d1df79c43";
  }

  static const char* value(const ::auto_smart_factory::PerformTaskTest&) { return value(); }
};

template<>
struct DataType< ::auto_smart_factory::PerformTaskTest > {
  static const char* value()
  {
    return "auto_smart_factory/PerformTaskTest";
  }

  static const char* value(const ::auto_smart_factory::PerformTaskTest&) { return value(); }
};


// service_traits::MD5Sum< ::auto_smart_factory::PerformTaskTestRequest> should match 
// service_traits::MD5Sum< ::auto_smart_factory::PerformTaskTest > 
template<>
struct MD5Sum< ::auto_smart_factory::PerformTaskTestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::PerformTaskTest >::value();
  }
  static const char* value(const ::auto_smart_factory::PerformTaskTestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::PerformTaskTestRequest> should match 
// service_traits::DataType< ::auto_smart_factory::PerformTaskTest > 
template<>
struct DataType< ::auto_smart_factory::PerformTaskTestRequest>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::PerformTaskTest >::value();
  }
  static const char* value(const ::auto_smart_factory::PerformTaskTestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_smart_factory::PerformTaskTestResponse> should match 
// service_traits::MD5Sum< ::auto_smart_factory::PerformTaskTest > 
template<>
struct MD5Sum< ::auto_smart_factory::PerformTaskTestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::PerformTaskTest >::value();
  }
  static const char* value(const ::auto_smart_factory::PerformTaskTestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::PerformTaskTestResponse> should match 
// service_traits::DataType< ::auto_smart_factory::PerformTaskTest > 
template<>
struct DataType< ::auto_smart_factory::PerformTaskTestResponse>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::PerformTaskTest >::value();
  }
  static const char* value(const ::auto_smart_factory::PerformTaskTestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_PERFORMTASKTEST_H
