// Generated by gencpp from file auto_smart_factory/RequestNewPathResponse.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_REQUESTNEWPATHRESPONSE_H
#define AUTO_SMART_FACTORY_MESSAGE_REQUESTNEWPATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace auto_smart_factory
{
template <class ContainerAllocator>
struct RequestNewPathResponse_
{
  typedef RequestNewPathResponse_<ContainerAllocator> Type;

  RequestNewPathResponse_()
    : new_path_nodes()
    , main_path_length(0)
    , is_last_chunk(false)  {
    }
  RequestNewPathResponse_(const ContainerAllocator& _alloc)
    : new_path_nodes(_alloc)
    , main_path_length(0)
    , is_last_chunk(false)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _new_path_nodes_type;
  _new_path_nodes_type new_path_nodes;

   typedef int32_t _main_path_length_type;
  _main_path_length_type main_path_length;

   typedef uint8_t _is_last_chunk_type;
  _is_last_chunk_type is_last_chunk;





  typedef boost::shared_ptr< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RequestNewPathResponse_

typedef ::auto_smart_factory::RequestNewPathResponse_<std::allocator<void> > RequestNewPathResponse;

typedef boost::shared_ptr< ::auto_smart_factory::RequestNewPathResponse > RequestNewPathResponsePtr;
typedef boost::shared_ptr< ::auto_smart_factory::RequestNewPathResponse const> RequestNewPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e9b541c1ac67c5922456a461c613f073";
  }

  static const char* value(const ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe9b541c1ac67c592ULL;
  static const uint64_t static_value2 = 0x2456a461c613f073ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/RequestNewPathResponse";
  }

  static const char* value(const ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Point[] new_path_nodes\n\
int32 main_path_length\n\
bool is_last_chunk\n\
\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.new_path_nodes);
      stream.next(m.main_path_length);
      stream.next(m.is_last_chunk);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RequestNewPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::RequestNewPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "new_path_nodes[]" << std::endl;
    for (size_t i = 0; i < v.new_path_nodes.size(); ++i)
    {
      s << indent << "  new_path_nodes[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.new_path_nodes[i]);
    }
    s << indent << "main_path_length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.main_path_length);
    s << indent << "is_last_chunk: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_last_chunk);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_REQUESTNEWPATHRESPONSE_H
