// Generated by gencpp from file auto_smart_factory/RequestNewPath.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_REQUESTNEWPATH_H
#define AUTO_SMART_FACTORY_MESSAGE_REQUESTNEWPATH_H

#include <ros/service_traits.h>


#include <auto_smart_factory/RequestNewPathRequest.h>
#include <auto_smart_factory/RequestNewPathResponse.h>


namespace auto_smart_factory
{

struct RequestNewPath
{

typedef RequestNewPathRequest Request;
typedef RequestNewPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RequestNewPath
} // namespace auto_smart_factory


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_smart_factory::RequestNewPath > {
  static const char* value()
  {
    return "fc441636b7a0cbdae9c6aa18043de91f";
  }

  static const char* value(const ::auto_smart_factory::RequestNewPath&) { return value(); }
};

template<>
struct DataType< ::auto_smart_factory::RequestNewPath > {
  static const char* value()
  {
    return "auto_smart_factory/RequestNewPath";
  }

  static const char* value(const ::auto_smart_factory::RequestNewPath&) { return value(); }
};


// service_traits::MD5Sum< ::auto_smart_factory::RequestNewPathRequest> should match 
// service_traits::MD5Sum< ::auto_smart_factory::RequestNewPath > 
template<>
struct MD5Sum< ::auto_smart_factory::RequestNewPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::RequestNewPath >::value();
  }
  static const char* value(const ::auto_smart_factory::RequestNewPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::RequestNewPathRequest> should match 
// service_traits::DataType< ::auto_smart_factory::RequestNewPath > 
template<>
struct DataType< ::auto_smart_factory::RequestNewPathRequest>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::RequestNewPath >::value();
  }
  static const char* value(const ::auto_smart_factory::RequestNewPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_smart_factory::RequestNewPathResponse> should match 
// service_traits::MD5Sum< ::auto_smart_factory::RequestNewPath > 
template<>
struct MD5Sum< ::auto_smart_factory::RequestNewPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::RequestNewPath >::value();
  }
  static const char* value(const ::auto_smart_factory::RequestNewPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::RequestNewPathResponse> should match 
// service_traits::DataType< ::auto_smart_factory::RequestNewPath > 
template<>
struct DataType< ::auto_smart_factory::RequestNewPathResponse>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::RequestNewPath >::value();
  }
  static const char* value(const ::auto_smart_factory::RequestNewPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_REQUESTNEWPATH_H
