// Generated by gencpp from file auto_smart_factory/ReserveStorageTray.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_RESERVESTORAGETRAY_H
#define AUTO_SMART_FACTORY_MESSAGE_RESERVESTORAGETRAY_H

#include <ros/service_traits.h>


#include <auto_smart_factory/ReserveStorageTrayRequest.h>
#include <auto_smart_factory/ReserveStorageTrayResponse.h>


namespace auto_smart_factory
{

struct ReserveStorageTray
{

typedef ReserveStorageTrayRequest Request;
typedef ReserveStorageTrayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReserveStorageTray
} // namespace auto_smart_factory


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_smart_factory::ReserveStorageTray > {
  static const char* value()
  {
    return "cff94141438e379e473614d183c5f213";
  }

  static const char* value(const ::auto_smart_factory::ReserveStorageTray&) { return value(); }
};

template<>
struct DataType< ::auto_smart_factory::ReserveStorageTray > {
  static const char* value()
  {
    return "auto_smart_factory/ReserveStorageTray";
  }

  static const char* value(const ::auto_smart_factory::ReserveStorageTray&) { return value(); }
};


// service_traits::MD5Sum< ::auto_smart_factory::ReserveStorageTrayRequest> should match 
// service_traits::MD5Sum< ::auto_smart_factory::ReserveStorageTray > 
template<>
struct MD5Sum< ::auto_smart_factory::ReserveStorageTrayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::ReserveStorageTray >::value();
  }
  static const char* value(const ::auto_smart_factory::ReserveStorageTrayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::ReserveStorageTrayRequest> should match 
// service_traits::DataType< ::auto_smart_factory::ReserveStorageTray > 
template<>
struct DataType< ::auto_smart_factory::ReserveStorageTrayRequest>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::ReserveStorageTray >::value();
  }
  static const char* value(const ::auto_smart_factory::ReserveStorageTrayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_smart_factory::ReserveStorageTrayResponse> should match 
// service_traits::MD5Sum< ::auto_smart_factory::ReserveStorageTray > 
template<>
struct MD5Sum< ::auto_smart_factory::ReserveStorageTrayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::ReserveStorageTray >::value();
  }
  static const char* value(const ::auto_smart_factory::ReserveStorageTrayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::ReserveStorageTrayResponse> should match 
// service_traits::DataType< ::auto_smart_factory::ReserveStorageTray > 
template<>
struct DataType< ::auto_smart_factory::ReserveStorageTrayResponse>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::ReserveStorageTray >::value();
  }
  static const char* value(const ::auto_smart_factory::ReserveStorageTrayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_RESERVESTORAGETRAY_H
