// Generated by gencpp from file auto_smart_factory/RetrievePackageResponse.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_RETRIEVEPACKAGERESPONSE_H
#define AUTO_SMART_FACTORY_MESSAGE_RETRIEVEPACKAGERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_smart_factory
{
template <class ContainerAllocator>
struct RetrievePackageResponse_
{
  typedef RetrievePackageResponse_<ContainerAllocator> Type;

  RetrievePackageResponse_()
    : storage_id(0)
    , estimated_time(0.0)  {
    }
  RetrievePackageResponse_(const ContainerAllocator& _alloc)
    : storage_id(0)
    , estimated_time(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _storage_id_type;
  _storage_id_type storage_id;

   typedef double _estimated_time_type;
  _estimated_time_type estimated_time;





  typedef boost::shared_ptr< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RetrievePackageResponse_

typedef ::auto_smart_factory::RetrievePackageResponse_<std::allocator<void> > RetrievePackageResponse;

typedef boost::shared_ptr< ::auto_smart_factory::RetrievePackageResponse > RetrievePackageResponsePtr;
typedef boost::shared_ptr< ::auto_smart_factory::RetrievePackageResponse const> RetrievePackageResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cf4a6afb292a74d3b885f54964349956";
  }

  static const char* value(const ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcf4a6afb292a74d3ULL;
  static const uint64_t static_value2 = 0xb885f54964349956ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/RetrievePackageResponse";
  }

  static const char* value(const ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 storage_id\n\
float64 estimated_time\n\
\n\
";
  }

  static const char* value(const ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.storage_id);
      stream.next(m.estimated_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RetrievePackageResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::RetrievePackageResponse_<ContainerAllocator>& v)
  {
    s << indent << "storage_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.storage_id);
    s << indent << "estimated_time: ";
    Printer<double>::stream(s, indent + "  ", v.estimated_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_RETRIEVEPACKAGERESPONSE_H
