// Generated by gencpp from file auto_smart_factory/RobotJourney.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_ROBOTJOURNEY_H
#define AUTO_SMART_FACTORY_MESSAGE_ROBOTJOURNEY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_smart_factory
{
template <class ContainerAllocator>
struct RobotJourney_
{
  typedef RobotJourney_<ContainerAllocator> Type;

  RobotJourney_()
    : id()
    , battery_consumption(0.0)
    , time_for_completion(0)
    , distance(0.0)  {
    }
  RobotJourney_(const ContainerAllocator& _alloc)
    : id(_alloc)
    , battery_consumption(0.0)
    , time_for_completion(0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  _id_type id;

   typedef float _battery_consumption_type;
  _battery_consumption_type battery_consumption;

   typedef int32_t _time_for_completion_type;
  _time_for_completion_type time_for_completion;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::auto_smart_factory::RobotJourney_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::RobotJourney_<ContainerAllocator> const> ConstPtr;

}; // struct RobotJourney_

typedef ::auto_smart_factory::RobotJourney_<std::allocator<void> > RobotJourney;

typedef boost::shared_ptr< ::auto_smart_factory::RobotJourney > RobotJourneyPtr;
typedef boost::shared_ptr< ::auto_smart_factory::RobotJourney const> RobotJourneyConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::RobotJourney_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::RobotJourney_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::RobotJourney_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::RobotJourney_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::RobotJourney_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::RobotJourney_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::RobotJourney_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::RobotJourney_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::RobotJourney_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88c56eff22bff62afcdddb15045697bc";
  }

  static const char* value(const ::auto_smart_factory::RobotJourney_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88c56eff22bff62aULL;
  static const uint64_t static_value2 = 0xfcdddb15045697bcULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::RobotJourney_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/RobotJourney";
  }

  static const char* value(const ::auto_smart_factory::RobotJourney_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::RobotJourney_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# robot id\n\
string id\n\
\n\
# battery consumption\n\
float32 battery_consumption\n\
\n\
# time it took to complete the task\n\
int32 time_for_completion\n\
\n\
# distance travelled\n\
float32 distance\n\
";
  }

  static const char* value(const ::auto_smart_factory::RobotJourney_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::RobotJourney_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.battery_consumption);
      stream.next(m.time_for_completion);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotJourney_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::RobotJourney_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::RobotJourney_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
    s << indent << "battery_consumption: ";
    Printer<float>::stream(s, indent + "  ", v.battery_consumption);
    s << indent << "time_for_completion: ";
    Printer<int32_t>::stream(s, indent + "  ", v.time_for_completion);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_ROBOTJOURNEY_H
