// Generated by gencpp from file auto_smart_factory/RotateTable.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_ROTATETABLE_H
#define AUTO_SMART_FACTORY_MESSAGE_ROTATETABLE_H

#include <ros/service_traits.h>


#include <auto_smart_factory/RotateTableRequest.h>
#include <auto_smart_factory/RotateTableResponse.h>


namespace auto_smart_factory
{

struct RotateTable
{

typedef RotateTableRequest Request;
typedef RotateTableResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RotateTable
} // namespace auto_smart_factory


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_smart_factory::RotateTable > {
  static const char* value()
  {
    return "f112e8d09c0b0824d371f81aa34bf8fd";
  }

  static const char* value(const ::auto_smart_factory::RotateTable&) { return value(); }
};

template<>
struct DataType< ::auto_smart_factory::RotateTable > {
  static const char* value()
  {
    return "auto_smart_factory/RotateTable";
  }

  static const char* value(const ::auto_smart_factory::RotateTable&) { return value(); }
};


// service_traits::MD5Sum< ::auto_smart_factory::RotateTableRequest> should match 
// service_traits::MD5Sum< ::auto_smart_factory::RotateTable > 
template<>
struct MD5Sum< ::auto_smart_factory::RotateTableRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::RotateTable >::value();
  }
  static const char* value(const ::auto_smart_factory::RotateTableRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::RotateTableRequest> should match 
// service_traits::DataType< ::auto_smart_factory::RotateTable > 
template<>
struct DataType< ::auto_smart_factory::RotateTableRequest>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::RotateTable >::value();
  }
  static const char* value(const ::auto_smart_factory::RotateTableRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_smart_factory::RotateTableResponse> should match 
// service_traits::MD5Sum< ::auto_smart_factory::RotateTable > 
template<>
struct MD5Sum< ::auto_smart_factory::RotateTableResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::RotateTable >::value();
  }
  static const char* value(const ::auto_smart_factory::RotateTableResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::RotateTableResponse> should match 
// service_traits::DataType< ::auto_smart_factory::RotateTable > 
template<>
struct DataType< ::auto_smart_factory::RotateTableResponse>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::RotateTable >::value();
  }
  static const char* value(const ::auto_smart_factory::RotateTableResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_ROTATETABLE_H
