// Generated by gencpp from file auto_smart_factory/SetPackage.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_SETPACKAGE_H
#define AUTO_SMART_FACTORY_MESSAGE_SETPACKAGE_H

#include <ros/service_traits.h>


#include <auto_smart_factory/SetPackageRequest.h>
#include <auto_smart_factory/SetPackageResponse.h>


namespace auto_smart_factory
{

struct SetPackage
{

typedef SetPackageRequest Request;
typedef SetPackageResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPackage
} // namespace auto_smart_factory


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::auto_smart_factory::SetPackage > {
  static const char* value()
  {
    return "2bf9725e18218d881c4e6def49493469";
  }

  static const char* value(const ::auto_smart_factory::SetPackage&) { return value(); }
};

template<>
struct DataType< ::auto_smart_factory::SetPackage > {
  static const char* value()
  {
    return "auto_smart_factory/SetPackage";
  }

  static const char* value(const ::auto_smart_factory::SetPackage&) { return value(); }
};


// service_traits::MD5Sum< ::auto_smart_factory::SetPackageRequest> should match 
// service_traits::MD5Sum< ::auto_smart_factory::SetPackage > 
template<>
struct MD5Sum< ::auto_smart_factory::SetPackageRequest>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::SetPackage >::value();
  }
  static const char* value(const ::auto_smart_factory::SetPackageRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::SetPackageRequest> should match 
// service_traits::DataType< ::auto_smart_factory::SetPackage > 
template<>
struct DataType< ::auto_smart_factory::SetPackageRequest>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::SetPackage >::value();
  }
  static const char* value(const ::auto_smart_factory::SetPackageRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::auto_smart_factory::SetPackageResponse> should match 
// service_traits::MD5Sum< ::auto_smart_factory::SetPackage > 
template<>
struct MD5Sum< ::auto_smart_factory::SetPackageResponse>
{
  static const char* value()
  {
    return MD5Sum< ::auto_smart_factory::SetPackage >::value();
  }
  static const char* value(const ::auto_smart_factory::SetPackageResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::auto_smart_factory::SetPackageResponse> should match 
// service_traits::DataType< ::auto_smart_factory::SetPackage > 
template<>
struct DataType< ::auto_smart_factory::SetPackageResponse>
{
  static const char* value()
  {
    return DataType< ::auto_smart_factory::SetPackage >::value();
  }
  static const char* value(const ::auto_smart_factory::SetPackageResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_SETPACKAGE_H
