// Generated by gencpp from file auto_smart_factory/StorageState.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_STORAGESTATE_H
#define AUTO_SMART_FACTORY_MESSAGE_STORAGESTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <auto_smart_factory/TrayState.h>

namespace auto_smart_factory
{
template <class ContainerAllocator>
struct StorageState_
{
  typedef StorageState_<ContainerAllocator> Type;

  StorageState_()
    : stamp()
    , tray_states()  {
    }
  StorageState_(const ContainerAllocator& _alloc)
    : stamp()
    , tray_states(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::vector< ::auto_smart_factory::TrayState_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::auto_smart_factory::TrayState_<ContainerAllocator> >::other >  _tray_states_type;
  _tray_states_type tray_states;





  typedef boost::shared_ptr< ::auto_smart_factory::StorageState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::StorageState_<ContainerAllocator> const> ConstPtr;

}; // struct StorageState_

typedef ::auto_smart_factory::StorageState_<std::allocator<void> > StorageState;

typedef boost::shared_ptr< ::auto_smart_factory::StorageState > StorageStatePtr;
typedef boost::shared_ptr< ::auto_smart_factory::StorageState const> StorageStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::StorageState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::StorageState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::StorageState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::StorageState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::StorageState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::StorageState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::StorageState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::StorageState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::StorageState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f58a17d0041d1e3c68f904805f0526cc";
  }

  static const char* value(const ::auto_smart_factory::StorageState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf58a17d0041d1e3cULL;
  static const uint64_t static_value2 = 0x68f904805f0526ccULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::StorageState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/StorageState";
  }

  static const char* value(const ::auto_smart_factory::StorageState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::StorageState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# timestamp of the state\n\
time stamp\n\
\n\
# States of the instances of the three tray types\n\
TrayState[] tray_states\n\
\n\
================================================================================\n\
MSG: auto_smart_factory/TrayState\n\
# the unique tray ID\n\
uint32 id\n\
\n\
# Indicates whether the tray is occupied or not.\n\
bool occupied\n\
\n\
# Availability of the tray. If false the the tray is allocated by a task.\n\
bool available\n\
\n\
# information about the package stored in this tray (only valid if state != free)\n\
Package package\n\
\n\
\n\
================================================================================\n\
MSG: auto_smart_factory/Package\n\
# the unique id of this package\n\
uint32 id\n\
\n\
# the id of the package type/configuration\n\
uint32 type_id\n\
\n\
";
  }

  static const char* value(const ::auto_smart_factory::StorageState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::StorageState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.tray_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StorageState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::StorageState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::StorageState_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "tray_states[]" << std::endl;
    for (size_t i = 0; i < v.tray_states.size(); ++i)
    {
      s << indent << "  tray_states[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::auto_smart_factory::TrayState_<ContainerAllocator> >::stream(s, indent + "    ", v.tray_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_STORAGESTATE_H
