// Generated by gencpp from file auto_smart_factory/TraySensor.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_TRAYSENSOR_H
#define AUTO_SMART_FACTORY_MESSAGE_TRAYSENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_smart_factory
{
template <class ContainerAllocator>
struct TraySensor_
{
  typedef TraySensor_<ContainerAllocator> Type;

  TraySensor_()
    : stamp()
    , tray_id(0)
    , occupied(false)
    , package()  {
    }
  TraySensor_(const ContainerAllocator& _alloc)
    : stamp()
    , tray_id(0)
    , occupied(false)
    , package(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef uint32_t _tray_id_type;
  _tray_id_type tray_id;

   typedef uint8_t _occupied_type;
  _occupied_type occupied;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _package_type;
  _package_type package;





  typedef boost::shared_ptr< ::auto_smart_factory::TraySensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::TraySensor_<ContainerAllocator> const> ConstPtr;

}; // struct TraySensor_

typedef ::auto_smart_factory::TraySensor_<std::allocator<void> > TraySensor;

typedef boost::shared_ptr< ::auto_smart_factory::TraySensor > TraySensorPtr;
typedef boost::shared_ptr< ::auto_smart_factory::TraySensor const> TraySensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::TraySensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::TraySensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::TraySensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::TraySensor_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::TraySensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::TraySensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::TraySensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::TraySensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::TraySensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "725e9e6d6f2ca4eb3fe26342aa2d5180";
  }

  static const char* value(const ::auto_smart_factory::TraySensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x725e9e6d6f2ca4ebULL;
  static const uint64_t static_value2 = 0x3fe26342aa2d5180ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::TraySensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/TraySensor";
  }

  static const char* value(const ::auto_smart_factory::TraySensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::TraySensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n\
\n\
# tray id\n\
uint32 tray_id\n\
\n\
# state of the tray: occupied/free\n\
bool occupied\n\
\n\
# name of the package if any is near\n\
string package\n\
\n\
";
  }

  static const char* value(const ::auto_smart_factory::TraySensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::TraySensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.tray_id);
      stream.next(m.occupied);
      stream.next(m.package);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TraySensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::TraySensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::TraySensor_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "tray_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.tray_id);
    s << indent << "occupied: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.occupied);
    s << indent << "package: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.package);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_TRAYSENSOR_H
