// Generated by gencpp from file auto_smart_factory/Tray.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_TRAY_H
#define AUTO_SMART_FACTORY_MESSAGE_TRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_smart_factory
{
template <class ContainerAllocator>
struct Tray_
{
  typedef Tray_<ContainerAllocator> Type;

  Tray_()
    : id(0)
    , type()
    , x(0.0)
    , y(0.0)
    , orientation(0.0)
    , max_load(0.0)
    , package_type(0)  {
    }
  Tray_(const ContainerAllocator& _alloc)
    : id(0)
    , type(_alloc)
    , x(0.0)
    , y(0.0)
    , orientation(0.0)
    , max_load(0.0)
    , package_type(0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _orientation_type;
  _orientation_type orientation;

   typedef float _max_load_type;
  _max_load_type max_load;

   typedef uint32_t _package_type_type;
  _package_type_type package_type;





  typedef boost::shared_ptr< ::auto_smart_factory::Tray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::Tray_<ContainerAllocator> const> ConstPtr;

}; // struct Tray_

typedef ::auto_smart_factory::Tray_<std::allocator<void> > Tray;

typedef boost::shared_ptr< ::auto_smart_factory::Tray > TrayPtr;
typedef boost::shared_ptr< ::auto_smart_factory::Tray const> TrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::Tray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::Tray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::Tray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::Tray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::Tray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::Tray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::Tray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::Tray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::Tray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4ebddf5eeb28c15170ac6457775fa846";
  }

  static const char* value(const ::auto_smart_factory::Tray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4ebddf5eeb28c151ULL;
  static const uint64_t static_value2 = 0x70ac6457775fa846ULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::Tray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/Tray";
  }

  static const char* value(const ::auto_smart_factory::Tray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::Tray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The representation of a warehouse tray\n\
\n\
# the unique identifier of this tray\n\
uint32 id\n\
\n\
# the type of the tray. Valid values: 'input', 'output' and 'storage'\n\
string type\n\
\n\
# the coordinates of the center of the tray in the '/map' frame\n\
float32 x\n\
float32 y\n\
\n\
# the yaw angle of the tray in the '/map' frame (ccw, in degree). Currently only multiples of 90 degree are supported.\n\
float32 orientation\n\
\n\
# maximum load, i.e. the maximum weight of packages to be put into this tray\n\
float32 max_load\n\
\n\
# package type this tray can carry. 0 means no constraints.\n\
uint32 package_type\n\
";
  }

  static const char* value(const ::auto_smart_factory::Tray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::Tray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.orientation);
      stream.next(m.max_load);
      stream.next(m.package_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Tray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::Tray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::Tray_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "orientation: ";
    Printer<float>::stream(s, indent + "  ", v.orientation);
    s << indent << "max_load: ";
    Printer<float>::stream(s, indent + "  ", v.max_load);
    s << indent << "package_type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.package_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_TRAY_H
