// Generated by gencpp from file auto_smart_factory/Wall.msg
// DO NOT EDIT!


#ifndef AUTO_SMART_FACTORY_MESSAGE_WALL_H
#define AUTO_SMART_FACTORY_MESSAGE_WALL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace auto_smart_factory
{
template <class ContainerAllocator>
struct Wall_
{
  typedef Wall_<ContainerAllocator> Type;

  Wall_()
    : x(0.0)
    , y(0.0)
    , orientation(0.0)  {
    }
  Wall_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , orientation(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _orientation_type;
  _orientation_type orientation;





  typedef boost::shared_ptr< ::auto_smart_factory::Wall_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::auto_smart_factory::Wall_<ContainerAllocator> const> ConstPtr;

}; // struct Wall_

typedef ::auto_smart_factory::Wall_<std::allocator<void> > Wall;

typedef boost::shared_ptr< ::auto_smart_factory::Wall > WallPtr;
typedef boost::shared_ptr< ::auto_smart_factory::Wall const> WallConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::auto_smart_factory::Wall_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::auto_smart_factory::Wall_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace auto_smart_factory

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'auto_smart_factory': ['/home/nishant/smart_factory_ss19_g3/src/auto_smart_factory/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::Wall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::auto_smart_factory::Wall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::Wall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::auto_smart_factory::Wall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::Wall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::auto_smart_factory::Wall_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::auto_smart_factory::Wall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1c567beaed44a5d11b818be4c87fec7b";
  }

  static const char* value(const ::auto_smart_factory::Wall_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1c567beaed44a5d1ULL;
  static const uint64_t static_value2 = 0x1b818be4c87fec7bULL;
};

template<class ContainerAllocator>
struct DataType< ::auto_smart_factory::Wall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "auto_smart_factory/Wall";
  }

  static const char* value(const ::auto_smart_factory::Wall_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::auto_smart_factory::Wall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# The representation of a warehouse wall\n\
\n\
# the coordinates of the center of the wall in the '/map' frame\n\
float32 x\n\
float32 y\n\
\n\
# the yaw angle of the tray in the '/map' frame (ccw, in degree). Currently only multiples of 90 degree are supported.\n\
float32 orientation\n\
\n\
\n\
";
  }

  static const char* value(const ::auto_smart_factory::Wall_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::auto_smart_factory::Wall_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.orientation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Wall_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::auto_smart_factory::Wall_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::auto_smart_factory::Wall_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "orientation: ";
    Printer<float>::stream(s, indent + "  ", v.orientation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AUTO_SMART_FACTORY_MESSAGE_WALL_H
